### ISSUE TITLE
Namespaces are included the class name

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverleague/silverstripe-ideannotator#101]
This is more of a feature request that issue.

Current output:

`* @method \DNADesign\Elemental\Models\ElementalArea ElementalArea()`

Desired output if `use` statement (`use DNADesign\Elemental\Models\ElementalArea;`) is already present:

` * @method ElementalArea ElementalArea()`

It would be great to add a configurable option for this output behaviour.

**Comment by Firesphere** [comment]
Absolutely agree, but with the current module, it's not possible, I think #91 might solve this?

I'm fairly sure it won't happen with the Generator 2.x, but 3.x might do the job :)
The biggest issue (assuming it'll resolve it?) is upgrading to 3.x.

At the moment, I stuck with 2.x because it made the initial upgrade a lot easier :) I do agree though, and upgrading to 3.x is on the list. A PR would be great if you have the time!

**Comment by Firesphere** [comment]
Resolved in #107 which uses ClassInfo to get shortnames if the config is set.

Feel free to have a PR @mfendeksilverstripe

**Comment by Firesphere** [comment]
Closing this in favor of the PR
