### ISSUE TITLE
What's the deal with the 3.0 tag?

### ISSUE THREAD

**Issue by hailwood** [silverleague/silverstripe-ideannotator#103]
So the readme states:

> Version ^2:
>
> SilverStripe 3.x framework
> Version ^3:
>
> SilverStripe 4.x

But we have a 3.0 tag that requires `silverstripe/framework: ^3.1`
https://packagist.org/packages/silverleague/ideannotator#3.0

Should this tag be removed or am I missing something here?

**Comment by robbieaverill** [comment]
You're right. 3.0 was released against SS3, while 3.0-alpha and beta are against SS4. I assume this was a mistake, but we can't really delete tags once they're out.

What we should do instead is update the SS4 version to 4.x and release a new set of tags that are semver compliant (4.0.0 rather than 4.0) etc

**Comment by hailwood** [comment]
So in the short term what should I be using in my SS 3 project? ~3.0, or ~2.0?

**Comment by robbieaverill** [comment]
2.x would be the safer option

**Comment by Firesphere** [comment]
2.x would do. And yes, it's my bad, I tagged it wrong. I'll get it sorted next week~ish :)
Thanks for pointing it out though!

**Comment by Firesphere** [comment]
It should be fixed in the more recent 3.x tags. 2.x is SS3
