### ISSUE TITLE
Annotatable::afterCallActionHandler should not return anything

### ISSUE THREAD

**Issue by lekoala** [silverleague/silverstripe-ideannotator#119]
returning true or false adds output to dev/build

```
Generating class docblocks

Docblock generation finished!

1
```

It would probably be better to use a flag to indicate that the generation has been done instead of returning true/false

No big deal but still, I scratch my head for a few minutes looking why I had this extra "1" at the end.

**Comment by robbieaverill** [comment]
Thanks for reporting. I notice that method has this doc block: `* @return bool // Return a boolean for test-purposes`

I agree that code for testing shouldn't affect use in the wild, and while this would probably be an API change I think we can probably do it in a patch release safely enough. Would you agree?

**Comment by lekoala** [comment]
it's probably not used outside of testing purposes so I would remove it yes.

**Comment by Firesphere** [comment]
The return true should be removed, the return `false` is for testing purposes, which should never show up if it's not enabled (true displays `1`, false displays nothing, afaik?)

A better approach for the tests would be however to check if the dockblock generation output is there or not instead of checking if the result is true or false :/ The finishig output should always be null.

**Comment by tractorcow** [comment]
Otherwise, inject a mock into annotator, and assert that `annotateModule` is called.

**Comment by Firesphere** [comment]
Changed to a dev issue. It is low priority, It's a minor annoyance to me.

**Comment by tractorcow** [comment]
Fixed; Please review :D
