### ISSUE TITLE
"Vendorise" module

### ISSUE THREAD

**Issue by robbieaverill** [silverleague/silverstripe-ideannotator#95]
SS4 supports "vendor modules" now.

This can be as simple as changing "silverstripe-module" to "silverstripe-vendormodule" in composer.json, and probably will be for this module since it doesn't have CSS or Javascript that need to be exposed for Requirements.

**Comment by Firesphere** [comment]
Yep, all for it 👍

**Comment by Firesphere** [comment]
Ehhh...
` "type": "silverstripe-vendormodule",`
It already is ;)

What _does_ need to be done however, is support modules possibly in the vendor folder. By default (current state), I'm not a fan of making it work out of the box though. Rather make it an option to explicitly say "yes I understand I'm touching vendor modules, just let me do it", instead of having vendor modules touched without the dev's knowledge

**Comment by axyr** [comment]
Should it not touch mysite code only as default?

**Comment by Firesphere** [comment]
Resolved in #100
